"""
Assignment 0 for CS-316

Author: Adam Rolek
Date: 1/23/2020
"""
import random


def check_win(computer_number, human_number):
    """
    This function compares the human and computer numbers

    :param computer_number: the number provided by the human
    :param human_number: the number generated by the program
    :return: True if the numbers match and False otherwise
    """
    return computer_number == human_number


def main():
    # Generating the computer number
    computer_number = random.randrange(0, 5)
    # Validating user input
    is_number = False
    while not is_number:
        try:
            human_number = int(input("input a number (0-5)> "))
            is_number = True
        except Exception as e:
            print("That was not a number!")
    # Generating some output and checking the win condition
    print("Computer: {}\nHuman: {}".format(computer_number, human_number))
    if check_win(computer_number, human_number):
        print("Winner!")
    else:
        print("Loser!")


if __name__ == "__main__":
    main()
